### ISSUE TITLE
username selector

### ISSUE THREAD

**Issue by idkjs** [emadehsan/thal#23]
At this point in your tut, [Extract Emails](https://medium.com/@e_mad_ehsan/getting-started-with-puppeteer-and-chrome-headless-for-web-scrapping-6bf5979dee3e#---0-14), when you selected the username selector in devtools, this is what I am getting:
```html
#user_search_results > div.user-list > div:nth-child(1) > div.d-flex > div > a > em
```

Note the `em` at then end. If you use this, the loop doesnt work. You have to change it to `#user_search_results > div.user-list > div:nth-child(1) > div.d-flex > div > a` for it to run.

Do you know why this might be happening?

Great tutorial. Thank you.

**Comment by emadehsan** [comment]
Hello Alain,

If you search for "john" you would see that if the username contains **john** GitHub would render it in bold. That's why the `<em>` tags. 
If username doesn't contain exact **john** then it wouldn't have `<em>` around it. See the red & blue circled names respectively.

**We want to select username in all cases. So, why not just select the `<a>` tag that has username as its `href` attribute!**

<hr>
<img src="https://user-images.githubusercontent.com/7283624/36064470-46714fda-0ead-11e8-8721-33608e52ca4e.png">
<hr>

**Comment by idkjs** [comment]
Nice. I had indeed copied the selector on a list item down the list somewhere so that makes sense.

Thank you, sir. Great post for me.
